### ISSUE TITLE
Open .jwb file and get items of Y-value

### ISSUE THREAD

**Issue by dinosauria123** [jzftran/jws2txt#1]
Hi !
Thank you for your jws2txt and I could make jwb2txt with small mod of your code.

.jwb file contains multiple measurements file.

I could get multiple Y-Values but does not get  items of Y-value from .jwb file.
Do you have any idea ?

I could see the structure of .jwb files via 7zip file manager.
Aside of DataInfo, MeasInfo, BaseInfo, and other Info files observed, but I could not decord them.

I ' ll attach my copy of jwb2txt.py for some kind of helps...
[jwb2txt.py.txt](https://github.com/jzftran/jws2txt/files/9127436/jwb2txt.py.txt)

Regards,

**Comment by dinosauria123** [comment]
I found Y-data items are stored in DataInfo
[Y-item_check.py.txt](https://github.com/jzftran/jws2txt/files/9127925/Y-item_check.py.txt)
.

**Comment by jzftran** [comment]
Hi,
I haven’t met with jwb file, so if you could send me such file it would be helpful.
Best
Jozef

Z poważaniem
Józef Tran

________________________________
Od: dinosauria123 ***@***.***>
Wysłane: Sunday, July 17, 2022 12:43:53 PM
Do: jzftran/jws2txt ***@***.***>
DW: Subscribed ***@***.***>
Temat: [jzftran/jws2txt] Open .jwb file and get items of Y-value (Issue #1)


Hi !
Thank you for your jws2txt and I could make jwb2txt with small mod of your code.

.jwb file contains multiple measurements file.

I could get multiple Y-Values but does not get items of Y-value from .jwb file.
Do you have any idea ?

I could see the structure of .jwb files via 7zip file manager.
Aside of DataInfo, MeasInfo, BaseInfo, and other Info files observed, but I could not decord them.

I ' ll attach my copy of jwb2txt.py for some kind of helps...
jwb2txt.py.txt<https://github.com/jzftran/jws2txt/files/9127436/jwb2txt.py.txt>

Regards,

**Comment by dinosauria123** [comment]
Thank you for your reply.

I found this : https://www.researchgate.net/post/Batch_export_processing_of_Jasco_interval_data_files_jwb_to_csv
This file seems to have Xdata:240-260 interval5, items of Y-data:300-600 intarvals2

Another data is attached:
 
[2022_05_14-1.zip](https://github.com/jzftran/jws2txt/files/9127989/2022_05_14-1.zip)
This file have Xdata:900-400 intervals 0.5, items of Y-data: 24.98 29.99 35 40 45 49.99 55 60.01

I hope this will help you.

**Comment by jzftran** [comment]
Hi,
I had a look at the second file you sent (2022_05_14-1.zip), thankfully it’s still an OLE-type file. Thanks to the information, you provided, how many channels this file contains I was able to decode it.
In general, the data contained in Y-data is stored in a linear form, that is, one string contains information about all channels, let's say we did a measurement on channel A, B and C then the data in Y-data will be in the form:
AAAAAAAAAABBBBBBBBCCCCCCCC

I should have more time in the next week to refine the script.

Od: ***@***.***>
Wysłano: niedziela, 17 lipca 2022 17:46
Do: ***@***.***>
DW: Józef ***@***.***>; ***@***.***>
Temat: Re: [jzftran/jws2txt] Open .jwb file and get items of Y-value (Issue #1)


Thank you for your reply.

I found this : https://www.researchgate.net/post/Batch_export_processing_of_Jasco_interval_data_files_jwb_to_csv
This file seems to have Xdata:240-260 interval5 Y-data:300-600 intarvals2

Another data is attached:

2022_05_14-1.zip<https://github.com/jzftran/jws2txt/files/9127989/2022_05_14-1.zip>
This file have Xdata:900-400 intervals 0.5 Y-data: 24.98 29.99 35 40 45 49.99 55 60.01

I hope this will help you.

**Comment by jzftran** [comment]
Hi @dinosauria123,
I've implemented the possibility to batch convert *.jwb files.
Right now jws2txt requires the user to type the number of channels the file contains. E.g *.jws file from Jasco spectropolarimeter may contain 3 channels: CD signal, UV signal, and HT voltage. So if you want to convert this file to *.txt you will need to input 3 in the command line.

**Comment by dinosauria123** [comment]
Thank you for your kindly helps.

I will check your code.
